services:
    kwc_contentapi.content_controller:
        class:    Kwc\ContentApiBundle\Controller\ContentController
        autowire: true

    kwc_contentapi.content_builder:
        class:    Kwc\ContentApiBundle\Services\ContentBuilder
        autowire: true
