services:
    kwc_content_api.content_controller:
        class:    Kwc\ContentApiBundle\Controller\ContentController
        arguments: ['@kwc_content_api.content_builder']

    kwc_content_api.content_builder:
        class:    Kwc\ContentApiBundle\Services\ContentBuilder
        autowire: true
